name: mtg_api
description: A Dart package for interacting with the MTG Scryfall API.
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.4

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  pedantic: ^1.8.0
  test: ^1.6.0
